# Generated by Django 5.1 on 2024-09-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutleeuser',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
