# Generated by Django 5.1 on 2024-10-02 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_alter_tutleeuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='student_pictures/')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_term_goals', models.TextField(blank=True, null=True)),
                ('long_term_goals', models.TextField(blank=True, null=True)),
                ('student', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_against_this_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prefrences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_of_interest', models.TextField(blank=True, null=True)),
                ('learning_goals', models.TextField(blank=True, null=True)),
                ('preferred_learning_style', models.CharField(blank=True, max_length=255, null=True)),
                ('study_schedule_preferences', models.TextField(blank=True, null=True)),
                ('mode_of_learning', models.CharField(blank=True, max_length=255, null=True)),
                ('tutoring_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency_of_tutoring', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_against_these_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
