# Generated by Django 5.1 on 2024-10-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0003_additioninfo_prefrences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionInfo',
            new_name='AdditionalInfo',
        ),
    ]
