# Generated by Django 5.1 on 2024-10-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0004_rename_additioninfo_additionalinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefrences',
            old_name='frequency_of_tutoring',
            new_name='frequency_of_tutoring_sessions',
        ),
    ]
